# Generated by Django 4.2.3 on 2024-02-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('clinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.cliente')),
            ],
        ),
    ]
