# Generated by Django 4.2.3 on 2024-02-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0003_estacionamento_valor_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
